# Generated by Django 3.0 on 2019-12-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Double_bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Room is available'), ('RESERVED', 'Room already reserved')], default='RESERVED', max_length=10)),
                ('issues', models.CharField(default='No Issues', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Single_bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Room is available'), ('RESERVED', 'Room already reserved')], default='RESERVED', max_length=10)),
                ('issues', models.CharField(default='No Issues', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
