# Generated by Django 3.0 on 2019-12-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Single_bed',
            new_name='SingleBed',
        ),
    ]
